import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { Layout } from "./components/layout";
import { ErrorBoundary } from "./components/error-boundary";
import { HomePage } from "./pages/home-page";
import { ShopPage } from "./pages/shop-page";
import { ProductPage } from "./pages/product-page";
import { CartPage } from "./pages/cart-page";
import { CheckoutPage } from "./pages/checkout-page";
import { LoginPage } from "./pages/login-page";
import { SignupPage } from "./pages/signup-page";
import { ContactPage } from "./pages/contact-page";
import { ThankYouPage } from "./pages/thank-you-page";
import { NotFoundPage } from "./pages/not-found-page";
import { AuthProvider } from "./context/auth-context";
import { CartProvider } from "./context/cart-context";
import "./styles/tokens.css";
import "./styles/app.css";
export const App = () => (_jsx(ErrorBoundary, { children: _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsx(CartProvider, { children: _jsx(Layout, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/shop", element: _jsx(ShopPage, {}) }), _jsx(Route, { path: "/products/:slug", element: _jsx(ProductPage, {}) }), _jsx(Route, { path: "/cart", element: _jsx(CartPage, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(CheckoutPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/signup", element: _jsx(SignupPage, {}) }), _jsx(Route, { path: "/contact", element: _jsx(ContactPage, {}) }), _jsx(Route, { path: "/thank-you", element: _jsx(ThankYouPage, {}) }), _jsx(Route, { path: "/index.html", element: _jsx(Navigate, { to: "/", replace: true }) }), _jsx(Route, { path: "/shop.html", element: _jsx(Navigate, { to: "/shop", replace: true }) }), _jsx(Route, { path: "/cart.html", element: _jsx(Navigate, { to: "/cart", replace: true }) }), _jsx(Route, { path: "/checkout.html", element: _jsx(Navigate, { to: "/checkout", replace: true }) }), _jsx(Route, { path: "/login.html", element: _jsx(Navigate, { to: "/login", replace: true }) }), _jsx(Route, { path: "/signup.html", element: _jsx(Navigate, { to: "/signup", replace: true }) }), _jsx(Route, { path: "/contact.html", element: _jsx(Navigate, { to: "/contact", replace: true }) }), _jsx(Route, { path: "/thank-you.html", element: _jsx(Navigate, { to: "/thank-you", replace: true }) }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }) }) }) }) }) }));
